---
# ArgoCD Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---
# ArgoCD Application CRD (will be used after ArgoCD installation)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supermarket-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abhishek-ai1/Prometheus_Grafana-Learning.git
    targetRevision: main
    path: supermarket-app/k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: supermarket
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 10
