---
# Auth Service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: supermarket
  labels:
    app: auth-service
spec:
  type: ClusterIP
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
    name: http
  selector:
    app: auth-service

---
# Customer Management Service
apiVersion: v1
kind: Service
metadata:
  name: customer-mgmt
  namespace: supermarket
  labels:
    app: customer-mgmt
spec:
  type: ClusterIP
  ports:
  - port: 5004
    targetPort: 5004
    protocol: TCP
    name: http
  selector:
    app: customer-mgmt

---
# BFF Service
apiVersion: v1
kind: Service
metadata:
  name: bff-service
  namespace: supermarket
  labels:
    app: bff-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: bff-service

---
# Core Service
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: supermarket
  labels:
    app: core-service
spec:
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: core-service

---
# UI Service
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: supermarket
  labels:
    app: ui-service
spec:
  type: LoadBalancer
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP
    name: http
  selector:
    app: ui-service
